#!/bin/bash
cd ..
unset GIT_DIR

NOW=$(date +"%Y%m%d-%H%M%S")
deploy_log="/var/logs/deploy/deploy-$NOW.log"
touch $deploy_log
exec > >(tee $deploy_log)
exec 2>&1

# Variables
NOW=$(date +"%Y%m%d-%H%M%S")
APPLICATION_DIR="`pwd`"
ROOT_DIR="`cd .. && pwd`"
BUILDS_DIR="$ROOT_DIR/builds"
BUILD_LOCATION="$BUILDS_DIR/$NOW"
SHARED_DIR="$ROOT_DIR/shared"
LATEST_SYMLINK="$ROOT_DIR/latest"

# Update dependencies
composer update  --no-dev

# Add symbolic links for shared data
rm -rf app/storage
ln -s $SHARED_DIR/storage app/storage

# Copy build
cp -rp $APPLICATION_DIR $BUILD_LOCATION

# Symbolic link from build to latest
ln -nsf $BUILD_LOCATION $LATEST_SYMLINK

# Remove older builds, keep 5
cd $BUILDS_DIR
rm -rf $(ls -1t | tail -n +6)
